2023-04-06 22:35:29,479 INFO    MainThread:19155 [wandb_setup.py:_flush():68] Configure stats pid to 19155
2023-04-06 22:35:29,480 INFO    MainThread:19155 [wandb_setup.py:_flush():68] Loading settings from /home/yx/.config/wandb/settings
2023-04-06 22:35:29,480 INFO    MainThread:19155 [wandb_setup.py:_flush():68] Loading settings from /mnt/c/kust/kust/python_code/python_code/code/experiments/unet/wandb/settings
2023-04-06 22:35:29,480 INFO    MainThread:19155 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-04-06 22:35:29,480 INFO    MainThread:19155 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program_relpath': 'myunet.py', 'program': '/mnt/c/kust/kust/python_code/python_code/code/experiments/unet/myunet.py'}
2023-04-06 22:35:29,492 INFO    MainThread:19155 [wandb_init.py:_log_setup():476] Logging user logs to ./runs/wandb/run-20230406_223529-2zzargz2/logs/debug.log
2023-04-06 22:35:29,492 INFO    MainThread:19155 [wandb_init.py:_log_setup():477] Logging internal logs to ./runs/wandb/run-20230406_223529-2zzargz2/logs/debug-internal.log
2023-04-06 22:35:29,492 INFO    MainThread:19155 [wandb_init.py:init():516] calling init triggers
2023-04-06 22:35:29,493 INFO    MainThread:19155 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {}
2023-04-06 22:35:29,493 INFO    MainThread:19155 [wandb_init.py:init():569] starting backend
2023-04-06 22:35:29,493 INFO    MainThread:19155 [wandb_init.py:init():573] setting up manager
2023-04-06 22:35:29,496 INFO    MainThread:19155 [backend.py:_multiprocessing_setup():102] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-04-06 22:35:29,500 INFO    MainThread:19155 [wandb_init.py:init():580] backend started and connected
2023-04-06 22:35:29,503 INFO    MainThread:19155 [wandb_init.py:init():658] updated telemetry
2023-04-06 22:35:29,513 INFO    MainThread:19155 [wandb_init.py:init():693] communicating run to backend with 60 second timeout
2023-04-06 22:36:29,571 ERROR   MainThread:19155 [wandb_init.py:init():704] backend process timed out
2023-04-06 22:36:29,571 ERROR   MainThread:19155 [wandb_init.py:init():713] encountered error: Error communicating with wandb process
For more info see: https://docs.wandb.ai/library/init#init-start-error
