2023-04-07 23:46:41,967 INFO    StreamThr :31084 [internal.py:wandb_internal():88] W&B internal server running at pid: 31084, started at: 2023-04-07 23:46:41.963910
2023-04-07 23:46:41,968 DEBUG   HandlerThread:31084 [handler.py:handle_request():139] handle_request: status
2023-04-07 23:46:41,973 DEBUG   SenderThread:31084 [sender.py:send_request():317] send_request: status
2023-04-07 23:46:41,974 DEBUG   SenderThread:31084 [sender.py:send():303] send: header
2023-04-07 23:46:41,974 INFO    WriterThread:31084 [datastore.py:open_for_write():75] open: ./runs/wandb/run-20230407_234641-1jg8nild/run-1jg8nild.wandb
2023-04-07 23:46:41,981 DEBUG   SenderThread:31084 [sender.py:send():303] send: run
2023-04-07 23:46:41,987 INFO    SenderThread:31084 [sender.py:_maybe_setup_resume():593] checking resume status for None/segmentation/1jg8nild
2023-04-07 23:46:46,995 DEBUG   HandlerThread:31084 [handler.py:handle_request():139] handle_request: keepalive
2023-04-07 23:46:52,003 DEBUG   HandlerThread:31084 [handler.py:handle_request():139] handle_request: keepalive
2023-04-07 23:46:57,009 DEBUG   HandlerThread:31084 [handler.py:handle_request():139] handle_request: keepalive
2023-04-07 23:47:01,464 DEBUG   HandlerThread:31084 [handler.py:handle_request():139] handle_request: check_version
2023-04-07 23:47:01,468 INFO    SenderThread:31084 [dir_watcher.py:__init__():216] watching files in: ./runs/wandb/run-20230407_234641-1jg8nild/files
2023-04-07 23:47:01,468 INFO    SenderThread:31084 [sender.py:_start_run_threads():928] run started: 1jg8nild with start time 1680882401.966375
2023-04-07 23:47:01,471 DEBUG   SenderThread:31084 [sender.py:send():303] send: summary
2023-04-07 23:47:01,475 INFO    SenderThread:31084 [sender.py:_save_file():1171] saving file wandb-summary.json with policy end
2023-04-07 23:47:01,476 DEBUG   SenderThread:31084 [sender.py:send_request():317] send_request: check_version
2023-04-07 23:47:02,471 INFO    Thread-13 :31084 [dir_watcher.py:_on_file_created():275] file/dir created: ./runs/wandb/run-20230407_234641-1jg8nild/files/wandb-summary.json
2023-04-07 23:47:03,043 DEBUG   HandlerThread:31084 [handler.py:handle_request():139] handle_request: run_start
2023-04-07 23:47:03,071 DEBUG   HandlerThread:31084 [system_info.py:__init__():31] System info init
2023-04-07 23:47:03,071 DEBUG   HandlerThread:31084 [system_info.py:__init__():46] System info init done
2023-04-07 23:47:03,071 INFO    HandlerThread:31084 [system_monitor.py:start():150] Starting system monitor
2023-04-07 23:47:03,072 INFO    SystemMonitor:31084 [system_monitor.py:_start():116] Starting system asset monitoring threads
2023-04-07 23:47:03,072 INFO    HandlerThread:31084 [system_monitor.py:probe():168] Collecting system info
2023-04-07 23:47:03,072 INFO    SystemMonitor:31084 [interfaces.py:start():168] Started cpu
2023-04-07 23:47:03,073 INFO    SystemMonitor:31084 [interfaces.py:start():168] Started disk
2023-04-07 23:47:03,074 INFO    SystemMonitor:31084 [interfaces.py:start():168] Started gpu
2023-04-07 23:47:03,075 INFO    SystemMonitor:31084 [interfaces.py:start():168] Started memory
2023-04-07 23:47:03,076 INFO    SystemMonitor:31084 [interfaces.py:start():168] Started network
2023-04-07 23:47:03,091 DEBUG   HandlerThread:31084 [system_info.py:probe():195] Probing system
2023-04-07 23:47:03,098 DEBUG   HandlerThread:31084 [git.py:repo():40] git repository is invalid
2023-04-07 23:47:03,098 DEBUG   HandlerThread:31084 [system_info.py:probe():241] Probing system done
2023-04-07 23:47:03,098 DEBUG   HandlerThread:31084 [system_monitor.py:probe():177] {'os': 'Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.31', 'python': '3.9.15', 'heartbeatAt': '2023-04-07T15:47:03.091495', 'startedAt': '2023-04-07T15:46:41.902632', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/mnt/c/kust/kust/python_code/python_code/code/experiments/unet/myunet.py', 'codePath': 'myunet.py', 'host': 'yangxiao', 'username': 'yx', 'executable': '/home/yx/miniconda3/envs/mat/bin/python', 'cpu_count': 8, 'cpu_count_logical': 16, 'cpu_freq': {'current': 3686.398999999999, 'min': 0.0, 'max': 0.0}, 'cpu_freq_per_core': [{'current': 3686.399, 'min': 0.0, 'max': 0.0}, {'current': 3686.399, 'min': 0.0, 'max': 0.0}, {'current': 3686.399, 'min': 0.0, 'max': 0.0}, {'current': 3686.399, 'min': 0.0, 'max': 0.0}, {'current': 3686.399, 'min': 0.0, 'max': 0.0}, {'current': 3686.399, 'min': 0.0, 'max': 0.0}, {'current': 3686.399, 'min': 0.0, 'max': 0.0}, {'current': 3686.399, 'min': 0.0, 'max': 0.0}, {'current': 3686.399, 'min': 0.0, 'max': 0.0}, {'current': 3686.399, 'min': 0.0, 'max': 0.0}, {'current': 3686.399, 'min': 0.0, 'max': 0.0}, {'current': 3686.399, 'min': 0.0, 'max': 0.0}, {'current': 3686.399, 'min': 0.0, 'max': 0.0}, {'current': 3686.399, 'min': 0.0, 'max': 0.0}, {'current': 3686.399, 'min': 0.0, 'max': 0.0}, {'current': 3686.399, 'min': 0.0, 'max': 0.0}], 'disk': {'total': 250.98248672485352, 'used': 16.917293548583984}, 'gpu': 'NVIDIA GeForce RTX 3060', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3060', 'memory_total': 12884901888}], 'memory': {'total': 15.537948608398438}}
2023-04-07 23:47:03,098 INFO    HandlerThread:31084 [system_monitor.py:probe():178] Finished collecting system info
2023-04-07 23:47:03,099 INFO    HandlerThread:31084 [system_monitor.py:probe():181] Publishing system info
2023-04-07 23:47:03,099 DEBUG   HandlerThread:31084 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-04-07 23:47:03,102 DEBUG   HandlerThread:31084 [system_info.py:_save_pip():67] Saving pip packages done
2023-04-07 23:47:03,103 DEBUG   HandlerThread:31084 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-04-07 23:47:03,480 INFO    Thread-13 :31084 [dir_watcher.py:_on_file_created():275] file/dir created: ./runs/wandb/run-20230407_234641-1jg8nild/files/requirements.txt
2023-04-07 23:47:03,481 INFO    Thread-13 :31084 [dir_watcher.py:_on_file_created():275] file/dir created: ./runs/wandb/run-20230407_234641-1jg8nild/files/conda-environment.yaml
2023-04-07 23:47:04,305 DEBUG   HandlerThread:31084 [system_info.py:_save_conda():86] Saving conda packages done
2023-04-07 23:47:04,313 INFO    HandlerThread:31084 [system_monitor.py:probe():183] Finished publishing system info
2023-04-07 23:47:04,331 DEBUG   SenderThread:31084 [sender.py:send():303] send: files
2023-04-07 23:47:04,331 INFO    SenderThread:31084 [sender.py:_save_file():1171] saving file wandb-metadata.json with policy now
2023-04-07 23:47:04,335 DEBUG   HandlerThread:31084 [handler.py:handle_request():139] handle_request: stop_status
2023-04-07 23:47:04,336 DEBUG   SenderThread:31084 [sender.py:send_request():317] send_request: stop_status
2023-04-07 23:47:04,495 INFO    Thread-13 :31084 [dir_watcher.py:_on_file_modified():292] file/dir modified: ./runs/wandb/run-20230407_234641-1jg8nild/files/conda-environment.yaml
2023-04-07 23:47:04,497 INFO    Thread-13 :31084 [dir_watcher.py:_on_file_created():275] file/dir created: ./runs/wandb/run-20230407_234641-1jg8nild/files/wandb-metadata.json
2023-04-07 23:47:05,652 DEBUG   HandlerThread:31084 [handler.py:handle_request():139] handle_request: poll_exit
2023-04-07 23:47:10,654 DEBUG   HandlerThread:31084 [handler.py:handle_request():139] handle_request: keepalive
2023-04-07 23:47:13,875 WARNING FileStreamThread:31084 [file_stream.py:request_with_retry():667] requests_with_retry encountered retryable exception: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')). func: <bound method Session.post of <requests.sessions.Session object at 0x7fbc35d59130>>, args: ('https://api.wandb.ai/files/yxwandb/segmentation/1jg8nild/file_stream',), kwargs: {'json': {'files': {'wandb-summary.json': {'offset': 0, 'content': ['{}']}}, 'dropped': 0}}
2023-04-07 23:47:15,655 DEBUG   HandlerThread:31084 [handler.py:handle_request():139] handle_request: keepalive
2023-04-07 23:47:20,657 DEBUG   HandlerThread:31084 [handler.py:handle_request():139] handle_request: keepalive
2023-04-07 23:47:23,387 DEBUG   SenderThread:31084 [sender.py:send():303] send: telemetry
2023-04-07 23:47:23,387 DEBUG   SenderThread:31084 [sender.py:send():303] send: metric
2023-04-07 23:47:23,388 DEBUG   SenderThread:31084 [sender.py:send():303] send: telemetry
2023-04-07 23:47:23,388 DEBUG   SenderThread:31084 [sender.py:send():303] send: metric
2023-04-07 23:47:23,388 WARNING SenderThread:31084 [sender.py:send_metric():1127] Seen metric with glob (shouldn't happen)
2023-04-07 23:47:23,388 DEBUG   SenderThread:31084 [sender.py:send():303] send: config
2023-04-07 23:47:23,391 DEBUG   SenderThread:31084 [sender.py:send():303] send: exit
2023-04-07 23:47:23,391 INFO    SenderThread:31084 [sender.py:send_exit():442] handling exit code: 1
2023-04-07 23:47:23,391 INFO    SenderThread:31084 [sender.py:send_exit():444] handling runtime: 1
2023-04-07 23:47:23,393 INFO    SenderThread:31084 [sender.py:_save_file():1171] saving file wandb-summary.json with policy end
2023-04-07 23:47:23,394 INFO    SenderThread:31084 [sender.py:send_exit():450] send defer
2023-04-07 23:47:23,394 DEBUG   SenderThread:31084 [sender.py:send_request():317] send_request: poll_exit
2023-04-07 23:47:23,394 DEBUG   HandlerThread:31084 [handler.py:handle_request():139] handle_request: defer
2023-04-07 23:47:23,394 INFO    HandlerThread:31084 [handler.py:handle_request_defer():162] handle defer: 0
2023-04-07 23:47:23,394 DEBUG   SenderThread:31084 [sender.py:send_request():317] send_request: defer
2023-04-07 23:47:23,395 INFO    SenderThread:31084 [sender.py:send_request_defer():459] handle sender defer: 0
2023-04-07 23:47:23,395 INFO    SenderThread:31084 [sender.py:transition_state():463] send defer: 1
2023-04-07 23:47:23,395 DEBUG   HandlerThread:31084 [handler.py:handle_request():139] handle_request: defer
2023-04-07 23:47:23,395 INFO    HandlerThread:31084 [handler.py:handle_request_defer():162] handle defer: 1
2023-04-07 23:47:23,395 INFO    HandlerThread:31084 [system_monitor.py:finish():160] Stopping system monitor
2023-04-07 23:47:23,396 DEBUG   SystemMonitor:31084 [system_monitor.py:_start():130] Starting system metrics aggregation loop
2023-04-07 23:47:23,396 INFO    HandlerThread:31084 [interfaces.py:finish():173] Joined cpu
2023-04-07 23:47:23,396 DEBUG   SystemMonitor:31084 [system_monitor.py:_start():137] Finished system metrics aggregation loop
2023-04-07 23:47:23,396 INFO    HandlerThread:31084 [interfaces.py:finish():173] Joined disk
2023-04-07 23:47:23,396 DEBUG   SystemMonitor:31084 [system_monitor.py:_start():141] Publishing last batch of metrics
2023-04-07 23:47:23,400 INFO    HandlerThread:31084 [interfaces.py:finish():173] Joined gpu
2023-04-07 23:47:23,400 INFO    HandlerThread:31084 [interfaces.py:finish():173] Joined memory
2023-04-07 23:47:23,400 INFO    HandlerThread:31084 [interfaces.py:finish():173] Joined network
2023-04-07 23:47:23,401 DEBUG   SenderThread:31084 [sender.py:send_request():317] send_request: defer
2023-04-07 23:47:23,401 INFO    SenderThread:31084 [sender.py:send_request_defer():459] handle sender defer: 1
2023-04-07 23:47:23,401 INFO    SenderThread:31084 [sender.py:transition_state():463] send defer: 2
2023-04-07 23:47:23,401 DEBUG   SenderThread:31084 [sender.py:send():303] send: stats
2023-04-07 23:47:23,401 DEBUG   HandlerThread:31084 [handler.py:handle_request():139] handle_request: defer
2023-04-07 23:47:23,402 INFO    HandlerThread:31084 [handler.py:handle_request_defer():162] handle defer: 2
2023-04-07 23:47:23,402 DEBUG   SenderThread:31084 [sender.py:send_request():317] send_request: defer
2023-04-07 23:47:23,402 INFO    SenderThread:31084 [sender.py:send_request_defer():459] handle sender defer: 2
2023-04-07 23:47:23,402 INFO    SenderThread:31084 [sender.py:transition_state():463] send defer: 3
2023-04-07 23:47:23,402 DEBUG   HandlerThread:31084 [handler.py:handle_request():139] handle_request: defer
2023-04-07 23:47:23,402 INFO    HandlerThread:31084 [handler.py:handle_request_defer():162] handle defer: 3
2023-04-07 23:47:23,403 DEBUG   SenderThread:31084 [sender.py:send_request():317] send_request: defer
2023-04-07 23:47:23,403 INFO    SenderThread:31084 [sender.py:send_request_defer():459] handle sender defer: 3
2023-04-07 23:47:23,403 INFO    SenderThread:31084 [sender.py:transition_state():463] send defer: 4
2023-04-07 23:47:23,403 DEBUG   HandlerThread:31084 [handler.py:handle_request():139] handle_request: defer
2023-04-07 23:47:23,403 INFO    HandlerThread:31084 [handler.py:handle_request_defer():162] handle defer: 4
2023-04-07 23:47:23,404 DEBUG   SenderThread:31084 [sender.py:send():303] send: summary
2023-04-07 23:47:23,405 INFO    SenderThread:31084 [sender.py:_save_file():1171] saving file wandb-summary.json with policy end
2023-04-07 23:47:23,406 DEBUG   SenderThread:31084 [sender.py:send_request():317] send_request: defer
2023-04-07 23:47:23,406 INFO    SenderThread:31084 [sender.py:send_request_defer():459] handle sender defer: 4
2023-04-07 23:47:23,406 INFO    SenderThread:31084 [sender.py:transition_state():463] send defer: 5
2023-04-07 23:47:23,407 DEBUG   HandlerThread:31084 [handler.py:handle_request():139] handle_request: defer
2023-04-07 23:47:23,407 INFO    HandlerThread:31084 [handler.py:handle_request_defer():162] handle defer: 5
2023-04-07 23:47:23,407 DEBUG   SenderThread:31084 [sender.py:send_request():317] send_request: defer
2023-04-07 23:47:23,407 INFO    SenderThread:31084 [sender.py:send_request_defer():459] handle sender defer: 5
2023-04-07 23:47:23,803 INFO    Thread-13 :31084 [dir_watcher.py:_on_file_modified():292] file/dir modified: ./runs/wandb/run-20230407_234641-1jg8nild/files/wandb-summary.json
2023-04-07 23:47:23,805 INFO    Thread-13 :31084 [dir_watcher.py:_on_file_created():275] file/dir created: ./runs/wandb/run-20230407_234641-1jg8nild/files/output.log
2023-04-07 23:47:25,659 DEBUG   HandlerThread:31084 [handler.py:handle_request():139] handle_request: keepalive
2023-04-07 23:47:25,821 INFO    Thread-13 :31084 [dir_watcher.py:_on_file_modified():292] file/dir modified: ./runs/wandb/run-20230407_234641-1jg8nild/files/output.log
2023-04-07 23:47:26,156 INFO    SenderThread:31084 [sender.py:transition_state():463] send defer: 6
2023-04-07 23:47:26,157 DEBUG   HandlerThread:31084 [handler.py:handle_request():139] handle_request: defer
2023-04-07 23:47:26,157 INFO    HandlerThread:31084 [handler.py:handle_request_defer():162] handle defer: 6
2023-04-07 23:47:26,157 DEBUG   SenderThread:31084 [sender.py:send_request():317] send_request: defer
2023-04-07 23:47:26,158 INFO    SenderThread:31084 [sender.py:send_request_defer():459] handle sender defer: 6
2023-04-07 23:47:26,826 INFO    Thread-13 :31084 [dir_watcher.py:_on_file_modified():292] file/dir modified: ./runs/wandb/run-20230407_234641-1jg8nild/files/config.yaml
2023-04-07 23:47:27,418 INFO    SenderThread:31084 [sender.py:transition_state():463] send defer: 7
2023-04-07 23:47:27,420 DEBUG   HandlerThread:31084 [handler.py:handle_request():139] handle_request: defer
2023-04-07 23:47:27,420 INFO    HandlerThread:31084 [handler.py:handle_request_defer():162] handle defer: 7
2023-04-07 23:47:27,421 DEBUG   SenderThread:31084 [sender.py:send_request():317] send_request: defer
2023-04-07 23:47:27,421 INFO    SenderThread:31084 [sender.py:send_request_defer():459] handle sender defer: 7
2023-04-07 23:47:27,432 INFO    SenderThread:31084 [dir_watcher.py:finish():362] shutting down directory watcher
2023-04-07 23:47:27,836 INFO    SenderThread:31084 [dir_watcher.py:_on_file_modified():292] file/dir modified: ./runs/wandb/run-20230407_234641-1jg8nild/files/output.log
2023-04-07 23:47:27,837 INFO    SenderThread:31084 [dir_watcher.py:finish():392] scan: ./runs/wandb/run-20230407_234641-1jg8nild/files
2023-04-07 23:47:27,870 INFO    SenderThread:31084 [dir_watcher.py:finish():406] scan save: ./runs/wandb/run-20230407_234641-1jg8nild/files/conda-environment.yaml conda-environment.yaml
2023-04-07 23:47:27,885 INFO    SenderThread:31084 [dir_watcher.py:finish():406] scan save: ./runs/wandb/run-20230407_234641-1jg8nild/files/config.yaml config.yaml
2023-04-07 23:47:27,896 INFO    SenderThread:31084 [dir_watcher.py:finish():406] scan save: ./runs/wandb/run-20230407_234641-1jg8nild/files/output.log output.log
2023-04-07 23:47:27,899 INFO    SenderThread:31084 [dir_watcher.py:finish():406] scan save: ./runs/wandb/run-20230407_234641-1jg8nild/files/requirements.txt requirements.txt
2023-04-07 23:47:27,903 INFO    SenderThread:31084 [dir_watcher.py:finish():406] scan save: ./runs/wandb/run-20230407_234641-1jg8nild/files/wandb-metadata.json wandb-metadata.json
2023-04-07 23:47:27,904 INFO    SenderThread:31084 [dir_watcher.py:finish():406] scan save: ./runs/wandb/run-20230407_234641-1jg8nild/files/wandb-summary.json wandb-summary.json
2023-04-07 23:47:27,907 INFO    SenderThread:31084 [sender.py:transition_state():463] send defer: 8
2023-04-07 23:47:27,908 DEBUG   HandlerThread:31084 [handler.py:handle_request():139] handle_request: defer
2023-04-07 23:47:27,908 INFO    HandlerThread:31084 [handler.py:handle_request_defer():162] handle defer: 8
2023-04-07 23:47:27,908 DEBUG   SenderThread:31084 [sender.py:send_request():317] send_request: defer
2023-04-07 23:47:27,908 INFO    SenderThread:31084 [sender.py:send_request_defer():459] handle sender defer: 8
2023-04-07 23:47:27,909 INFO    SenderThread:31084 [file_pusher.py:finish():168] shutting down file pusher
2023-04-07 23:47:30,661 DEBUG   HandlerThread:31084 [handler.py:handle_request():139] handle_request: keepalive
2023-04-07 23:47:33,672 INFO    Thread-19 :31084 [upload_job.py:push():143] Uploaded file ./runs/wandb/run-20230407_234641-1jg8nild/files/output.log
2023-04-07 23:47:33,763 INFO    Thread-20 :31084 [upload_job.py:push():143] Uploaded file ./runs/wandb/run-20230407_234641-1jg8nild/files/requirements.txt
2023-04-07 23:47:35,663 DEBUG   HandlerThread:31084 [handler.py:handle_request():139] handle_request: keepalive
2023-04-07 23:47:37,727 INFO    Thread-21 :31084 [upload_job.py:push():143] Uploaded file ./runs/wandb/run-20230407_234641-1jg8nild/files/wandb-summary.json
2023-04-07 23:47:40,665 DEBUG   HandlerThread:31084 [handler.py:handle_request():139] handle_request: keepalive
2023-04-07 23:47:45,668 DEBUG   HandlerThread:31084 [handler.py:handle_request():139] handle_request: keepalive
2023-04-07 23:47:50,670 DEBUG   HandlerThread:31084 [handler.py:handle_request():139] handle_request: keepalive
2023-04-07 23:47:50,949 INFO    Thread-17 :31084 [upload_job.py:push():143] Uploaded file ./runs/wandb/run-20230407_234641-1jg8nild/files/conda-environment.yaml
2023-04-07 23:47:55,671 DEBUG   HandlerThread:31084 [handler.py:handle_request():139] handle_request: keepalive
2023-04-07 23:48:00,673 DEBUG   HandlerThread:31084 [handler.py:handle_request():139] handle_request: keepalive
2023-04-07 23:48:01,383 INFO    Thread-18 :31084 [upload_job.py:push():143] Uploaded file ./runs/wandb/run-20230407_234641-1jg8nild/files/config.yaml
2023-04-07 23:48:05,677 DEBUG   HandlerThread:31084 [handler.py:handle_request():139] handle_request: keepalive
2023-04-07 23:48:10,669 ERROR   Thread-16 :31084 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/yxwandb/segmentation/1jg8nild/wandb-metadata.json?Expires=1680968875&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=ZQM2t2gE%2BE81Gpp3JJ0OgkuWTez9SLjVUqozxvWtIVyt0pIjcrdMnSEemdiiARjpXSqTqnCxm48q6QWmZGhH1kotcXBunhqKN2dgt8TDNLFdzPkQkyM1Gw05V4cvlFMrhReCQdJtK00X96EM70YXfTZlL%2FdktsLs5uemDm4FV6ylVZ0cMLjzcS%2Fz%2FKg846xke0LNIO8qILXlfoLpGQG2m6atD3TWdFIuZV2c9ff%2BzfDCBbdAjmu8cleMbnpEqrZl9vw0excJbjZvqkG0Mp6lqj4Tqr%2B9QxWxpbBv2x83K%2BhO9d%2BCKhNF7TyT3eMzjn%2FO176jDhkA5ZIMRMDGWTYiEQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/yxwandb/segmentation/1jg8nild/wandb-metadata.json?Expires=1680968875&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=ZQM2t2gE%2BE81Gpp3JJ0OgkuWTez9SLjVUqozxvWtIVyt0pIjcrdMnSEemdiiARjpXSqTqnCxm48q6QWmZGhH1kotcXBunhqKN2dgt8TDNLFdzPkQkyM1Gw05V4cvlFMrhReCQdJtK00X96EM70YXfTZlL%2FdktsLs5uemDm4FV6ylVZ0cMLjzcS%2Fz%2FKg846xke0LNIO8qILXlfoLpGQG2m6atD3TWdFIuZV2c9ff%2BzfDCBbdAjmu8cleMbnpEqrZl9vw0excJbjZvqkG0Mp6lqj4Tqr%2B9QxWxpbBv2x83K%2BhO9d%2BCKhNF7TyT3eMzjn%2FO176jDhkA5ZIMRMDGWTYiEQ%3D%3D (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))
2023-04-07 23:48:10,670 ERROR   Thread-16 :31084 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2648'}
2023-04-07 23:48:10,671 ERROR   Thread-16 :31084 [internal_api.py:upload_file():1930] upload_file response body: 
2023-04-07 23:48:10,678 DEBUG   HandlerThread:31084 [handler.py:handle_request():139] handle_request: keepalive
2023-04-07 23:48:15,680 DEBUG   HandlerThread:31084 [handler.py:handle_request():139] handle_request: keepalive
2023-04-07 23:48:20,684 DEBUG   HandlerThread:31084 [handler.py:handle_request():139] handle_request: keepalive
2023-04-07 23:48:22,287 ERROR   Thread-16 :31084 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/yxwandb/segmentation/1jg8nild/wandb-metadata.json?Expires=1680968875&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=ZQM2t2gE%2BE81Gpp3JJ0OgkuWTez9SLjVUqozxvWtIVyt0pIjcrdMnSEemdiiARjpXSqTqnCxm48q6QWmZGhH1kotcXBunhqKN2dgt8TDNLFdzPkQkyM1Gw05V4cvlFMrhReCQdJtK00X96EM70YXfTZlL%2FdktsLs5uemDm4FV6ylVZ0cMLjzcS%2Fz%2FKg846xke0LNIO8qILXlfoLpGQG2m6atD3TWdFIuZV2c9ff%2BzfDCBbdAjmu8cleMbnpEqrZl9vw0excJbjZvqkG0Mp6lqj4Tqr%2B9QxWxpbBv2x83K%2BhO9d%2BCKhNF7TyT3eMzjn%2FO176jDhkA5ZIMRMDGWTYiEQ%3D%3D: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2023-04-07 23:48:22,288 ERROR   Thread-16 :31084 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2648'}
2023-04-07 23:48:22,289 ERROR   Thread-16 :31084 [internal_api.py:upload_file():1930] upload_file response body: 
2023-04-07 23:48:25,686 DEBUG   HandlerThread:31084 [handler.py:handle_request():139] handle_request: keepalive
2023-04-07 23:48:30,691 DEBUG   HandlerThread:31084 [handler.py:handle_request():139] handle_request: keepalive
2023-04-07 23:48:35,101 WARNING StreamThr :31084 [internal.py:is_dead():385] Internal process exiting, parent pid 31001 disappeared
2023-04-07 23:48:35,101 ERROR   StreamThr :31084 [internal.py:wandb_internal():147] Internal process shutdown.
2023-04-07 23:48:35,423 INFO    WriterThread:31084 [datastore.py:close():279] close: ./runs/wandb/run-20230407_234641-1jg8nild/run-1jg8nild.wandb
2023-04-07 23:48:35,691 DEBUG   HandlerThread:31084 [handler.py:handle_request():139] handle_request: keepalive
2023-04-07 23:48:35,692 INFO    HandlerThread:31084 [handler.py:finish():814] shutting down handler
2023-04-07 23:48:35,923 INFO    SenderThread:31084 [sender.py:finish():1331] shutting down sender
2023-04-07 23:48:35,923 INFO    SenderThread:31084 [file_pusher.py:finish():168] shutting down file pusher
2023-04-07 23:48:35,923 INFO    SenderThread:31084 [file_pusher.py:join():173] waiting for file pusher
2023-04-07 23:48:37,768 ERROR   Thread-16 :31084 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/yxwandb/segmentation/1jg8nild/wandb-metadata.json?Expires=1680968875&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=ZQM2t2gE%2BE81Gpp3JJ0OgkuWTez9SLjVUqozxvWtIVyt0pIjcrdMnSEemdiiARjpXSqTqnCxm48q6QWmZGhH1kotcXBunhqKN2dgt8TDNLFdzPkQkyM1Gw05V4cvlFMrhReCQdJtK00X96EM70YXfTZlL%2FdktsLs5uemDm4FV6ylVZ0cMLjzcS%2Fz%2FKg846xke0LNIO8qILXlfoLpGQG2m6atD3TWdFIuZV2c9ff%2BzfDCBbdAjmu8cleMbnpEqrZl9vw0excJbjZvqkG0Mp6lqj4Tqr%2B9QxWxpbBv2x83K%2BhO9d%2BCKhNF7TyT3eMzjn%2FO176jDhkA5ZIMRMDGWTYiEQ%3D%3D: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2023-04-07 23:48:37,768 ERROR   Thread-16 :31084 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2648'}
2023-04-07 23:48:37,769 ERROR   Thread-16 :31084 [internal_api.py:upload_file():1930] upload_file response body: 
2023-04-07 23:48:37,769 ERROR   Thread-16 :31084 [retry.py:__call__():154] Retry attempt failed:
Traceback (most recent call last):
  File "/home/yx/miniconda3/envs/mat/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/yx/miniconda3/envs/mat/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/yx/miniconda3/envs/mat/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/home/yx/miniconda3/envs/mat/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/home/yx/miniconda3/envs/mat/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/home/yx/miniconda3/envs/mat/lib/python3.9/http/client.py", line 289, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yx/miniconda3/envs/mat/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/yx/miniconda3/envs/mat/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/yx/miniconda3/envs/mat/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/yx/miniconda3/envs/mat/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/home/yx/miniconda3/envs/mat/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/yx/miniconda3/envs/mat/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/yx/miniconda3/envs/mat/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/home/yx/miniconda3/envs/mat/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/home/yx/miniconda3/envs/mat/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/home/yx/miniconda3/envs/mat/lib/python3.9/http/client.py", line 289, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yx/miniconda3/envs/mat/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 1923, in upload_file
    response = requests.put(url, data=progress, headers=extra_headers)
  File "/home/yx/miniconda3/envs/mat/lib/python3.9/site-packages/requests/api.py", line 134, in put
    return request('put', url, data=data, **kwargs)
  File "/home/yx/miniconda3/envs/mat/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/yx/miniconda3/envs/mat/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/yx/miniconda3/envs/mat/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/yx/miniconda3/envs/mat/lib/python3.9/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yx/miniconda3/envs/mat/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 113, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/yx/miniconda3/envs/mat/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 1950, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/home/yx/miniconda3/envs/mat/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 1923, in upload_file
    response = requests.put(url, data=progress, headers=extra_headers)
  File "/home/yx/miniconda3/envs/mat/lib/python3.9/site-packages/requests/api.py", line 134, in put
    return request('put', url, data=data, **kwargs)
  File "/home/yx/miniconda3/envs/mat/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/yx/miniconda3/envs/mat/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/yx/miniconda3/envs/mat/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/yx/miniconda3/envs/mat/lib/python3.9/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
wandb.sdk.lib.retry.TransientError: None
2023-04-07 23:48:53,731 INFO    Thread-16 :31084 [upload_job.py:push():143] Uploaded file /tmp/tmp9_huxikswandb/oxckh302-wandb-metadata.json
2023-04-07 23:48:53,932 INFO    Thread-12 :31084 [sender.py:transition_state():463] send defer: 9
